apiVersion: v1
kind: Pod
metadata:
  name: sg-app
spec:
  containers:
    - name: sg-app
      image: centos
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args:
        ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
      volumeMounts:
        - mountPath: /data
          name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-claim
