apiVersion: v1
kind: Pod
metadata:
  name: stateful-app
spec:
  containers:
    - name: stateful-app
      image: centos
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "while true; do echo $(date -u) >> /tmp/data/out.txt; sleep 5; done",
        ]
      volumeMounts:
        - mountPath: /tmp/data
          name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
